```{r, eval=TRUE, echo=TRUE}
devtools::load_all (".", export_all = FALSE)
#devtools::load_all (".", export_all = FALSE, recompile = TRUE)
#devtools::load_all (".")
devtools::document (".")
devtools::run_examples ()
devtools::test ()
devtools::check (".")
devtools::build_vignettes (".")
goodpractice::gp (".")
#devtools::spell_check ()
```

```{r}
devtools::load_all (".", export_all = FALSE)
library (sf)
plot_bus_stops ("kathmandu", d = 750)
plot_bus_stops ("kathmandu", d = 750, buildings = TRUE)
```

## bus stops to activity spaces

```{r}
devtools::load_all ("../dodgr", export_all = FALSE)
devtools::load_all ("../m4ra", export_all = FALSE)
devtools::load_all (".", export_all = FALSE)
library (sf)
city <- "kathmandu"
graph <- get_street_network (city = city)
bldg <- get_buildings (city = city) # can take a long time
pts_bus_activity <- flow_points (city, type = "bus-activity",
                                 graph, bldg)
pts_bus_residential <- flow_points (city, type = "bus-residential",
                                    graph, bldg)
pts_activity <- flow_points (city, type = "activity", graph, bldg)
pts_residential <- flow_points (city, type = "residential", graph, bldg)
```
```{r}
save (pts_bus_activity, file = "pts_bus_activity.rda")
save (pts_bus_residential, file = "pts_bus_residential.rda")
save (pts_activity, file = "pts_activity.rda")
save (pts_residential, file = "pts_residential.rda")
```
```{r}
devtools::load_all ("../dodgr", export_all = FALSE)
devtools::load_all ("../m4ra", export_all = FALSE)
devtools::load_all (".", export_all = FALSE)
library (sf)
city <- "kathmandu"
graph <- get_street_network (city = city)
load ("pts_bus_activity.rda")
load ("pts_bus_residential.rda")
load ("pts_activity.rda")
load ("pts_residential.rda")
```

```{r}
f1 <- flow_layer (graph, from = pts_bus_activity,
                to = pts_activity, k = 1, fname = NULL, city = city)
f2 <- flow_layer (graph, from = pts_activity,
                to = pts_bus_activity, k = 1, fname = NULL, city = city)
f3 <- flow_layer (graph, from = pts_residential,
                to = pts_bus_residential, k = 1, fname = NULL, city = city)
f4 <- flow_layer (graph, from = pts_bus_residential,
                to = pts_residential, k = 1, fname = NULL, city = city)
#save (f, file = "f.rda")
```
```{r}
plot_flows (f1, limit = 0.01)
```

```{r}
devtools::load_all (".", export_all = TRUE)
from <- pts_bus_residential
to <- pts_residential
k <- 1
pts <- unique (c (from$node, to$node))
graph <- get_street_network (city = city, verts = pts)
dens <- rep (0, nrow (graph$verts))
#dens [match (to$node, graph$verts$id)] <- to$density
length (which (!to$node %in% graph$verts$id))
length (to$node)
```

